import express from 'express';
import path from 'path';
import { createServer as createViteServer } from 'vite';
import { GoogleGenAI } from '@google/genai';

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

async function startServer() {
  const app = express();
  const PORT = 3000;

  // Increase payload limit for large OCR text chunks
  app.use(express.json({ limit: '50mb' }));

  app.post('/api/clean-text', async (req, res) => {
    try {
      const { text } = req.body;
      if (!text) {
        return res.status(400).json({ error: 'Text is required' });
      }

      const response = await ai.models.generateContent({
        model: 'gemini-3.6-flash',
        contents: text,
        config: {
          systemInstruction: "You are an expert OCR text cleaner and formatter. Your task is to take raw, messy text extracted via OCR and clean it perfectly, outputting properly structured Markdown. You MUST fix typos, remove random artifact characters (like random floating punctuation, gibberish, or mojibake generated by bad scans), fix broken line breaks, and repair broken sentences.\n\nCRITICAL RULES:\n1. NEVER summarize or remove actual meaningful content, paragraphs, or sentences.\n2. Keep the exact original meaning and full information.\n3. Preserve complex layouts! If the original text contains tables, format them as Markdown tables. If it has headers, use Markdown headers. Preserve lists and code blocks.\n4. Return ONLY the formatted Markdown text. Do not include any conversational filler (e.g., 'Here is the cleaned text').\n5. Maintain the page dividers if they exist (e.g., --- Page 1 ---).",
          temperature: 0.1,
        }
      });

      res.json({ cleanedText: response.text });
    } catch (error: any) {
      console.error('Error cleaning text:', error);
      res.status(500).json({ error: error.message });
    }
  });

  // Vite middleware setup for development
  if (process.env.NODE_ENV !== 'production') {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, '0.0.0.0', () => {
    console.log(`Server running on port ${PORT}`);
  });
}

startServer();
